### ISSUE TITLE
UX: Messages Redesign

### ISSUE THREAD

**Issue by beneboy** [stencila/hub#166]
Currently messages appear as temporary toasts at the bottom of the screen. This is not ideal when the messages may contain a lot of information (for example, "Please install the GitHub application to continue, it can be installed at https://github.com/stencila/some/long/path").

As part of UX improvements the message display should be also considered.

Potentially allow inclusion of a close button for dismissing the messages.

**Comment by nokome** [comment]
Was about to start a new message suggesting that we need a redesign on messages and saw this one still open. So using it.

As a user I have been finding the messages UI not that useful. Because they are inline, at the top, they cause 'jumpiness' - everything below them get's shifted down - and often away from where the user focus is - the button I jest pressed. Because they are light coloured they are easy to not see at all (ie. the screen just jumped but I'm not sure why).

![image](https://user-images.githubusercontent.com/1152336/77861274-62571800-7270-11ea-9e05-0afcc86b6200.png)

_In this particular case the message is not necessary because the user get's the visual feedback in the list of "Who has access". But that is another topic_

I'd prefer to go back to toasts that appear with animation and close after some time, or can be manually closed.

**Comment by nokome** [comment]
Since we are already using Buefy: https://buefy.org/documentation/snackbar
