### ISSUE TITLE
Creating file: fix error with the path

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#172]
Not sure if this is just about the error message - probably it is. Should be something more like " YYYY path does not exist, please choose the correct one" ?

![image](https://user-images.githubusercontent.com/2358535/50330171-1ee70780-055f-11e9-8685-0de7b7da3f88.png)

**Comment by beneboy** [comment]
It does not allow _ either. I think that was how it was originally implemented but I can not see why they would not be allowed.

**Comment by beneboy** [comment]
None of the paths really "exist" so you can create a file with any path as long as it passes the regex test:
`^[^/][A-Za-z\-/\.]+[^/]$'`

**Comment by apawlik** [comment]
Thanks. I guess we will know from user tests how to deal with that. I *think* these paths on paper (don't know what's the terminology) may be confusing. We will see

**Comment by beneboy** [comment]
Yes, I think that what we will end up with is the ability to create a file inside a directory, and just give it a name, rather than using a full path. This is difficult at the moment because we don't have the concept of directories just paths to files, and we generate the directory listings in a virtual manner

**Comment by beneboy** [comment]
I have pushed a fix so any character is allowed in the path.
