### ISSUE TITLE
Log unapplied migrations message somewhere

### ISSUE THREAD

**Issue by beneboy** [stencila/hub#208]
If the rollout to the new pod does not take place because migrations have not been applied, we should log it somewhere (sentry or syslog) so it's clear why K8s has not rolled to the updated pod.

**Comment by nokome** [comment]
This is now being done. Sentry events are generated every 10s with each status check made by k8s but only one email goes out per "issue". After the migration is done the issue should be "Resolved" so that a new alert email is generated next time. The events include the version number of the new release (2.5.3 in this case) - this could potentially be used to more-automatically resolve which k8s deployment to exec into to manually apply the migration.

![image](https://user-images.githubusercontent.com/1152336/78071980-d4f3ff00-73fa-11ea-8ac9-b84bd0fceec1.png)

cc @alex-ketch
