### ISSUE TITLE
docker compose for process orchestration

### ISSUE THREAD

**Issue by almereyda** [stencila/hub#24]
As the Stencila environment already makes good use of docker for various build environments, it is imaginable also to serve the Stencila Hub via a swarm of Docker containers, linked together via an examplanatory `docker-compose.yml` file.

How should such an image look like to support dynamic scaling of the different roles?

**Comment by nokome** [comment]
Thanks for the suggestion @almereyda . I have considered this but didn't think it was a priority ATM. I don't have experience with Compose so not sure what a `docker-compose.yml` would look like.

The main need for dynamic scaling is in the `worker` role - scaling up to support more sessions, scaling down to reduce compute resource consumption. I made the decision to implement that internally rather than use Compose (or something like AWS EC2 Container Service) to allow for more flexibility in the provisioning of worker instances. For example, someone doing some compute intensive analysis or wanted extra security for their data might want to have a session provisioned for a few hours on a dedicated VM or even use their own machines. Perhaps, you could still have that flexibility using Compose or something similar but at the time it felt easier to roll-our-own.

Currently that dynamic scaling is (very partially) implemented in [`Worker.choose()`][/director/sessions_/models.py]. Near the top of my to do list is to implement a `Worker.scale()` method to pre-emptively scale up and down worker instances.

**Comment by apawlik** [comment]
The Stencila Hub architecture has changed since - closing then.
