### ISSUE TITLE
Thema version updates policy

### ISSUE THREAD

**Issue by giorgiosironi** [stencila/hub#367]
Stencila Hub [currently uses Thema 1.16](https://github.com/stencila/hub/search?q=thema&unscoped_q=thema).

[eLife developers have been expanding the eLife theme](https://github.com/stencila/thema/pulls?q=is%3Apr+elife) to allow embedding of https://hub.stenci.la/elife/30274/files/preview/article-30274.md (via a custom CNAME) into an iframe.

Thema has reached [2.1.0](https://github.com/stencila/thema/releases/tag/v2.1.0) so it would be good to know how/if/when this can get into Stencila Hub, and further changes can propagate as more of the eLife theme is built.

**Comment by nokome** [comment]
Hi @giorgiosironi. Thanks for raising this issue. @alex-ketch , @beneboy and I were discussing this very point last week but haven't yet actioned it.

There are a few option for updating which version of Thema are used on the Hub:

1. Manually update
  - :-1: time consuming
  - :-1: easy to forget to do
2. Major version redirect: use unpkg links like `https://unpkg.com/@stencila/thema@2/dist/themes/stencila/styles.css` (as I have done in #357) which will mean that the client will be redirected to the most recent v2.X.X:
  - :+1: least time consuming option
  - :+1: new releases of Thema are used as soon as they are released
  - :-1: no control of the exact version of Thema used e.g. is a regression requires a rollback to a previous version
3. Encoda (which is already a dependency of Hub) to reexport the version of Thema being used and Hub uses that version:
  - :+1: greater guarantee that the version of Thema being used is compatible with the HTML being generated by the version of Encoda being used (although that is less likely to be an issue going foward)
  - :-1: would slow down the availability of Thema releases in the Hub because there would be one more link in the dependency chain
  - :-1: requires code to get the version of Thema into HTML templates
4. Pin Thema in `package.json` `dependencies` and rely on Renovate to notify of us of updates (current weekly, but could be more, or less, frequent):
  - :-1: requires code to get the version of Thema into HTML templates
 - :+1: allows to also extract an up-to-date list of theme names to allow the user to select from
  - :+1: provides a good balance between having regular updates to Thema while still being able to rollback / or not update as necessary.
  - :+1: one line change (in 'package.json') for contributors to make when submitting a PR to update Thema

I'll create a PR for option 4 now and ask for some reviews.

**Comment by giorgiosironi** [comment]
Just stating that `2` would also :-1:  create some headache with caching as the `Cache-Control: public, s-maxage=600, max-age=60` may cause cached assets of a major version to expire at slightly different times, using the CSS from one minor version and the JS from another for example.
