### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by simonwinter** [stencila/hub#415]
When I build the hub from the root dir via `make`, the director fails to build the docker image at the following step:

```bash
Step 7/15 : COPY package*.json /home/
ERROR: Service 'director' failed to build: COPY failed: no source files were specified
make: *** [build] Error 1
```

As it says in the error message, there are no `package*.json` files in the director package.

**Comment by nokome** [comment]
Thanks for reporting this. It's all a bit hacky at the moment.

The `package.json` file gets copied from the top dir to the `director` dir here (but it should also be done prior to doing `docker-compose up --build` too):

https://github.com/stencila/hub/blob/master/director/Makefile#L112-L115

This is hopefully a temporary situation caused by the following...

1. The `director` currently shells out to the npm package `@stencila/encoda` to do conversions
2. So `encoda` needs to be in the `director`'s image.
3. Rather than hard code the `encoda` version in the `Dockerfile` or in another `package.json` we put it in the top level `package.json`

I'm planning to move the conversion stuff into a Job and remove Encoda from the `director`'s image.
