### ISSUE TITLE
Automatically merge user accounts based on OAuth client email address

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#467]
After researching this a little again, the best thread, with the most concrete solutions and recent comments is this one: https://github.com/pennersr/django-allauth/issues/418#issuecomment-107880925 (starting there and going down). 

That provides a strategy for connecting a new social account to an existing Django account. It uses exact email matches. We might also want to consider close matches, including names not just emails, and present the user with a list of those similar accounts which they may instead want to authenticate with (and then link the new social account to after?). Recognising that there are several security concerns here.

Also to note that this issue was originally suggesting something simpler - just keeping a cookie that suggests to the user that they re-authenticate on the Hub using the same social account as last time.

_Originally posted by @nokome in https://github.com/stencila/hub/issues/8#issuecomment-595528259_

**Comment by richardmansfield** [comment]
Partially fixed in https://github.com/stencila/hub/pull/474, which will do automatic merging on signup provided the matching emails are verified on both sides. Google oauth emails are already treated as verified by django-allauth, but an extra request has been added to get the verified status of github email addresses.

For twitter and ORCID, we need to check if email verification status is provided as a part of the auth response and dealt with appropriately by allauth. If it is not, we most likely still need to add in an api request.
