### ISSUE TITLE
Add ability to preview Project file contents

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#607]
To build confidence that conversions are working, know whether a file has been updated, explore a project, and overall be more productive, we'd like to show a preview of project files.

**Current view (we'd like to enrich)**

![Screenshot 2020-08-05 at 11 23 57](https://user-images.githubusercontent.com/1646307/89431829-69a29c80-d70e-11ea-8446-63862af2780d.png)

**Comment by nokome** [comment]
This is not straight forward given our current architecture which aims to decouple a project's working directory from the `manager`. Instead the `worker`s work on the working directory and report back to the `manager` (file size, fingerprint etc). This architecture envisages people being able run their own workers on their own infrastructure. To maintain this ability, I see two alternatives to being able to preview file contents):

1. `worker` adds the file contents to the information it reports back with; the `manager` stores it and serves it up when someone wants a preview

2. `worker` (or some other process) serves the working directory directly and the `manager` asynchronously loads a preview of the content

An alternative, in the short term is for the `manager` to simply mount our NFS drive and serve the files - for this preview and for serving of "live" project files https://github.com/stencila/hub/issues/601. That should be implemented so that we can switch to option 2, maybe on a per worker / account bases, in the future.

**Comment by nokome** [comment]
Done :tada: 

![image](https://user-images.githubusercontent.com/1152336/89725273-cf21c080-da61-11ea-854c-e5afdda442ee.png)
